### ISSUE TITLE
change span to button ?

### ISSUE THREAD

**Issue by frehner** [blittle/racial-equity-banner#2]
I'm not an accessibility expert, so I don't know for sure how accessible this span is. Seems like it may be easier to maybe change it to a button though

https://github.com/blittle/allies/blob/e13aaa1a8e8388f159f43d6e5f6c8f7a134bbaf5/allies.js#L94

**Comment by blittle** [comment]
The reason I didn't use a button is because many websites already style a button, and getting a complete reset could be difficult. If there is another aria prop to add, I think it would be easier to do that

**Comment by filoxo** [comment]
To make this accessible, you should also add `tabindex="0"` so that the element is focusable, as well as handle keyboard events that correspond to click ("Enter" and "Space"). I can create a PR in a few unless someone else would like to take this on. Additional info here: https://filoxo.github.io/accessible-buttons/
